site_name: Great Yellow Eng Docs
site_url: https://greatyellow.earth/docs
theme:
  name: material
  logo: assets/download.png
  favicon: assets/favicon.ico
  features:
  - navigation.footer
  - content.code.copy
  - content.code.select
  - content.code.annotate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: custom
      accent: green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: amber
      accent: green
plugins:
  - search
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css
  - css/status-icons.css
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/great-yellow
    - icon: fontawesome/solid/globe
      link: https://greatyellow.earth
  status:
    draft: draft          # Shows a pencil/edit icon
    approved: approved  # Shows a checkmark icon
copyright: Copyright &copy; 2025 Great Yellow